#include "Instruction.h"

#define MNEMONIC_ADD_KEY_VALUE(k, v) m_MnemonicMap[k] = v
#define OPERAND_ADD_KEY_VALUE(k, v) m_OperandMap[k] = v

Instruction::Instruction()
	: m_cPrefix(0)
	, m_dwOpcode(0)
	, m_cModRM(0)
	, m_cSIB(0)
	, m_Mnemonic(MNEMONIC::NON)
	, m_Operand1(REGISTER::NON)
	, m_Operand2(REGISTER::NON)
	, m_bIsDisplacementValid(FALSE)
	, m_dwDisplacement(0)
	, m_bIsImmediateValid(FALSE)
	, m_dwImmediate(0)
	, m_dwSize(0)
{
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::MOV, "MOV");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::ADD, "ADD");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::SUB, "SUB");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::INC, "INC");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::DEC, "DEC");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::XOR, "XOR");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::CMP, "CMP");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::JMP, "JMP");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::JNE, "JNE");
	MNEMONIC_ADD_KEY_VALUE(MNEMONIC::TST, "TEST");

	OPERAND_ADD_KEY_VALUE(REGISTER::AL, "AL");
	OPERAND_ADD_KEY_VALUE(REGISTER::AH, "AH");
	OPERAND_ADD_KEY_VALUE(REGISTER::BL, "BL");
	OPERAND_ADD_KEY_VALUE(REGISTER::BH, "BH");
	OPERAND_ADD_KEY_VALUE(REGISTER::CL, "CL");
	OPERAND_ADD_KEY_VALUE(REGISTER::CH, "CH");
	OPERAND_ADD_KEY_VALUE(REGISTER::DL, "DL");
	OPERAND_ADD_KEY_VALUE(REGISTER::DH, "DH");
	OPERAND_ADD_KEY_VALUE(REGISTER::AX, "AX");
	OPERAND_ADD_KEY_VALUE(REGISTER::BX, "BX");
	OPERAND_ADD_KEY_VALUE(REGISTER::CX, "CX");
	OPERAND_ADD_KEY_VALUE(REGISTER::DX, "DX");
	OPERAND_ADD_KEY_VALUE(REGISTER::SI, "SI");
	OPERAND_ADD_KEY_VALUE(REGISTER::DI, "DI");
	OPERAND_ADD_KEY_VALUE(REGISTER::EAX, "EAX");
	OPERAND_ADD_KEY_VALUE(REGISTER::EBX, "EBX");
	OPERAND_ADD_KEY_VALUE(REGISTER::ECX, "ECX");
	OPERAND_ADD_KEY_VALUE(REGISTER::EDX, "EDX");
	OPERAND_ADD_KEY_VALUE(REGISTER::ESI, "ESI");
	OPERAND_ADD_KEY_VALUE(REGISTER::EDI, "EDI");
	OPERAND_ADD_KEY_VALUE(REGISTER::EBP, "EBP");
	OPERAND_ADD_KEY_VALUE(REGISTER::ESP, "ESP");
	OPERAND_ADD_KEY_VALUE(REGISTER::RAX, "RAX");
	OPERAND_ADD_KEY_VALUE(REGISTER::RBX, "RBX");
	OPERAND_ADD_KEY_VALUE(REGISTER::RCX, "RCX");
	OPERAND_ADD_KEY_VALUE(REGISTER::RDX, "RDX");
	OPERAND_ADD_KEY_VALUE(REGISTER::RSI, "RSI");
	OPERAND_ADD_KEY_VALUE(REGISTER::RDI, "RDI");
	OPERAND_ADD_KEY_VALUE(REGISTER::RBP, "RBP");
	OPERAND_ADD_KEY_VALUE(REGISTER::RSP, "RSP");
}